### ISSUE TITLE
Could u translate to english for eu server 

### ISSUE THREAD

**Issue by DarthRambo007** [danggai/android_genshin_resin_widget#24]
i like the ui he customisation on android only problem is i cant transfer my ac using methods provided i'm on android sns

**Comment by danggai** [comment]
I'm sorry for the late confirmation.

May I know if the translation you mentioned means in-game mail message or in-app language?

In-game mail messages are delivered in the language set by the app.

You can use the upper left button on the main screen of the current app to set the language in the app to English or Korean.
